nombre=input('Ingrese su nombre: ')
print('hola!',nombre)
apellido=input('Cual es su apellido: ')
print('Es un gusto Sr ',apellido)
direccion=input('Necesito su direccion:')
print('Muachas gracias ')
edad=input('Por ultimo, cual es su edad:')
print('correcto, estamos buscando personas que tengan', edad ,'años de edad, que ayuden en nuestra empresa y que vivan por el sur de Quito,',direccion,' , en este caso y sera tomado en cuenta en para el puesto de trabajo como Ingeniero Electronico ')